### ISSUE TITLE
missing library

### ISSUE THREAD

**Issue by thomasX** [joergkeller/beehive-sensor#16]
i hava tried to compile the current project, but i  get the error "LoRaMac.h: No such file or directory"

it looks like one submodule is missing

**Comment by emilvi** [comment]
I got the same issue. I seems to be an issue with CubeCell board version 1.3.0
Go into Tools / Board: .... / Boards Manager and downgrade CubeCell to 1.2.0 or 1.1.0

**Comment by joergkeller** [comment]
The project is updated to CubeCell 1.3.0. There was no submodule missing, but CubeCell core moved the LoRaMac.h, so I had to change the include.
